### ISSUE TITLE
Help: Interpreting Rorschach plots?

### ISSUE THREAD

**Issue by ChristopherEeles** [gustaveroussy/EaCoN#24]
Hello @aoumess,

Thanks for all the fixes to this pipeline. We are still using it in our lab.

Just curious if you could point me to some documentation on how to interpret the Rorschach plots output by ASCAT with Affymetrix (Thermofischer) and Oncoscan arrays?

I spend some time Googling it but couldn't find any references. We would like to improve our QC for the pipeline and interpreting these plots seems like a good first step to that.

Thanks for your assistance.

Best,
Christopher Eeles | Software Developer | BHKLab @ PM-Research | UHN

**Comment by aoumess** [comment]
Hi Christopher !

What I call "Rorscharch plots" are everything but a standard name, it's just a funny name we chose because their shape strikingly reminded us the famous Rorschach images used by shrinks to help people express their inner feelings (and, to another extent, the character from the Watchmen comics ;p).
It's simply a graphical representation of the log2ratio in function of the B-allele frequency, a representation used in quite any paper that treats of absolute copy number inference (see by example the Fig7 of https://www.archives-ouvertes.fr/hal-01108425/document). It is just an aesthetic way to visualize what links L2R and BAF to define absolute copy number levels.
In our version, each panel correspond to a chromosome. On the L2R version, all bins are plotted on each panel in dark grey, and those corresponding to the chromosome of the corresponding panel are in green. On the ASCN version (named Rorschach "clown"), all bins are still plotted on each chromosome panel, still in dark grey by default, but this time the color used for the bins corresponding to the chromosome of each panel changes in function of its absolute CN level.

I hope this will help you ? If you have more questions, do not hesitate asking !

Best regards,

Bastien

**Comment by ChristopherEeles** [comment]
Thanks Bastien. I will give that paper a read and let you know if I have further questions.

Best,
Chris
